#!/usr/bin/env python3
"""
Generate WP-CLI commands to delete products before consolidation import.

This creates shell commands that can be run on the WordPress server to:
1. Trash the existing simple products that will become variations
2. Allow the consolidated variable products to be imported

Usage:
    python scripts/generate_wpcli_cleanup.py > outputs/woo_consolidation/cleanup_commands.sh
    # Then run on WP server: bash cleanup_commands.sh
"""

import csv
import sys
from pathlib import Path


def main():
    delete_csv = Path("outputs/woo_consolidation/products_to_delete.csv")
    
    if not delete_csv.exists():
        print(f"Error: {delete_csv} not found. Run consolidation first.", file=sys.stderr)
        sys.exit(1)
    
    print("#!/bin/bash")
    print("# WP-CLI commands to delete products before consolidation import")
    print("# Generated by generate_wpcli_cleanup.py")
    print()
    print("# IMPORTANT: Run this on your WordPress server BEFORE importing consolidated_products.csv")
    print("# This will TRASH (not permanently delete) the products. They can be restored if needed.")
    print()
    print("set -e  # Exit on error")
    print()
    
    product_ids = []
    skus = []
    
    with open(delete_csv, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get('ID'):
                product_ids.append(row['ID'])
            elif row.get('SKU'):
                skus.append(row['SKU'])
    
    print(f"# Total products to delete: {len(product_ids) + len(skus)}")
    print()
    
    # Group into batches of 50 for efficiency
    batch_size = 50
    
    if product_ids:
        print("# Delete by product ID (faster)")
        for i in range(0, len(product_ids), batch_size):
            batch = product_ids[i:i+batch_size]
            ids_str = " ".join(batch)
            print(f'wp post delete {ids_str} --force')
    
    if skus:
        print()
        print("# Delete by SKU (for products without IDs)")
        for sku in skus:
            # Escape SKU for shell
            safe_sku = sku.replace("'", "'\"'\"'")
            print(f"wp wc product delete $(wp wc product list --sku='{safe_sku}' --field=id --user=1) --force --user=1 2>/dev/null || true")
    
    print()
    print("echo 'Cleanup complete! Now import consolidated_products.csv via WooCommerce > Products > Import'")


if __name__ == "__main__":
    main()
